# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3up < Formula
  desc ""
  homepage ""
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xtatsux/s3up/releases/download/v0.5.1/s3up_Darwin_x86_64.tar.gz"
      sha256 "49119beca312b7737413df638b43b27a0e4ccd3c1d62245c2158fc9e610c5f39"

      def install
        bin.install "s3up"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xtatsux/s3up/releases/download/v0.5.1/s3up_Darwin_arm64.tar.gz"
      sha256 "1d1b861a9b461042cd556dd4705d4457642c88d165030ecdd30e5682dca9b064"

      def install
        bin.install "s3up"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xtatsux/s3up/releases/download/v0.5.1/s3up_Linux_x86_64.tar.gz"
        sha256 "c82c7dd0b837f2ff1dee6e80f5faeb5a00eac9fcb1cd0534e3249949a3a52f05"

        def install
          bin.install "s3up"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xtatsux/s3up/releases/download/v0.5.1/s3up_Linux_arm64.tar.gz"
        sha256 "6dcbbeb551b63deba76bf5483be73ac987e24a85f54376448783d87347d32af6"

        def install
          bin.install "s3up"
        end
      end
    end
  end
end
