# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class S3up < Formula
  desc ""
  homepage ""
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xtatsux/s3up/releases/download/v0.6.1/s3up_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ed8d3dacd70d8152b6db36a13c275564153181898adbd75d9c0e6971bef8f5dd"

      def install
        bin.install "s3up"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xtatsux/s3up/releases/download/v0.6.1/s3up_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "71393114a8f4be81d746fe9058d0a8092145fba486e7f06d578d3b1fd94380c5"

      def install
        bin.install "s3up"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/xtatsux/s3up/releases/download/v0.6.1/s3up_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "53d87041c715511c0f3c4d3e548aa3368eefcec77fb604af62bb380fd38e13c1"
      def install
        bin.install "s3up"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/xtatsux/s3up/releases/download/v0.6.1/s3up_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "85ed8d3917ef69f199ecb5de9eba3418c0b672bdced7d53db007c49fdc02e282"
      def install
        bin.install "s3up"
      end
    end
  end
end
